services:
  app:
    image: node:lts
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3002'
    command: sh -c "PORT=3002 npm install && npm run dev"
    depends_on:
      - mongo
      - truffle
    networks:
      - nft-digio-network

  truffle:
    image: trufflesuite/ganache-cli
    restart: always
    platform: linux/amd64
    ports:
      - '7545:7545'
    volumes:
      - ./contracts:/contracts
    networks:
      - nft-digio-network

  mongo:
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - nft-digio-network

volumes:
  dbdata:

networks:
  nft-digio-network:
    driver: bridge